# Generated by Django 6.0.1 on 2026-01-27 15:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64)),
                ('city_name_en', models.CharField(max_length=64, null=True)),
                ('city_name_ru', models.CharField(max_length=64, null=True)),
                ('city_image', models.ImageField(blank=True, null=True, upload_to='city_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64)),
                ('country_name_en', models.CharField(max_length=64, null=True)),
                ('country_name_ru', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=64)),
                ('district_name_en', models.CharField(max_length=64, null=True)),
                ('district_name_ru', models.CharField(max_length=64, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('title_ru', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('room', 'room'), ('plot', 'plot'), ('dacha', 'dacha'), ('parking/garage', 'parking/garage     ')], max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('address_en', models.CharField(max_length=150, null=True)),
                ('address_ru', models.CharField(max_length=150, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('total_floors', models.PositiveSmallIntegerField()),
                ('condition', models.CharField(choices=[('self-finishing', 'self-finishing'), ('euro renovation', 'euro renovation'), ('good', 'good'), ('average', 'average'), ('not completed', 'not completed')], max_length=35)),
                ('condition_en', models.CharField(choices=[('self-finishing', 'self-finishing'), ('euro renovation', 'euro renovation'), ('good', 'good'), ('average', 'average'), ('not completed', 'not completed')], max_length=35, null=True)),
                ('condition_ru', models.CharField(choices=[('self-finishing', 'self-finishing'), ('euro renovation', 'euro renovation'), ('good', 'good'), ('average', 'average'), ('not completed', 'not completed')], max_length=35, null=True)),
                ('documents', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.property')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=64)),
                ('region_name_en', models.CharField(max_length=64, null=True)),
                ('region_name_ru', models.CharField(max_length=64, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.country')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.region'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
